version: '3'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - HOGE=hogehoge
    ports:
      - "3000:3000"
      - "3001:3001"
